# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/frontend

variables:
  - name: backendProjectSrc
    value: 'src/backend/**/*.csproj'
  - name: vmImageLinux
    value: 'ubuntu-latest'
    
    # necessário pra rodar as sql migrations
  - name: vmImageWindows
    value: 'windows-latest'

stages:
  - stage: DEV
    jobs:
      - job: CD_App
        pool:
          vmImage: $(vmImageLinux)
        displayName: 'CD App'
        steps:
          - task: Docker@2
            displayName: 'login docker'
            inputs:
              containerRegistry: 'docker-registry'
              command: 'login'
          - task: CmdLine@2
            inputs:
              script: 'echo $(Build.Repository.LocalPath)'
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-registry'
              repository: 'ja-reclamou-hoje-api'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)'
              tags: 'JaReclamouHojeApi_$(Build.BuildId)'